{{- if .Values.rbac.install }}
{{- if eq "cluster" .Values.configuration.scope }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: litmus-admin-cluster-role-binding
  labels:
    name: litmus-admin-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: litmus-admin-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountAdminName }}
    namespace: {{ .Release.Namespace }}

{{- end  }}
{{- end  }}