apiVersion: v1
kind: ConfigMap
metadata:
  name: subscriber-config
  namespace: {{ .Release.Namespace }}
data:
  SERVER_ADDR: {{ .Values.configuration.serverAddress }}
  INFRA_SCOPE: {{ .Values.configuration.infraScope }}
  VERSION: {{ .Values.configuration.version }}
  START_TIME: "1742678427545"
  SKIP_SSL_VERIFY: {{ .Values.configuration.skipSSLVerify }}
  CUSTOM_TLS_CERT: {{ .Values.configuration.customTLSCertificate }}
  IS_INFRA_CONFIRMED: {{ .Values.configuration.isInfrastructureConfirmed }}
  COMPONENTS: |
    DEPLOYMENTS: ["app=chaos-exporter", "name=chaos-operator", "app=event-tracker", "app=workflow-controller"]
