apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: {{ .Release.Namespace }}
data:
  containerRuntimeExecutor: k8sapi
  executor: |
    imagePullPolicy: IfNotPresent
  instanceID:  {{ .Values.configuration.instanceID  }}
