{{- if .Values.rbac.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infra-ops-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infra-ops-role
subjects:
  - kind: ServiceAccount
    name: litmus
    namespace: l{{ .Release.Namespace }}

{{- end  }}