apiVersion: v1
kind: Secret
metadata:
  name: subscriber-secret
  namespace: {{ .Release.Namespace }}
stringData:
  INFRA_ID: {{ .Values.configuration.instanceID  }} # TODO
  ACCESS_KEY: {{ .Values.configuration.accessKey  }}  # TODO
