{{- if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus-admin
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.rbac.serviceAccountAdminName }}

{{- end  }}