name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1 
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.13.0

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.x

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi


      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml --lint-conf lintconf.yaml --chart-yaml-schema chart_schema.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        if: steps.list-changed.outputs.changed == 'true'

      - run: |
          kubectl cluster-info 
          kubectl get nodes -v=6
          helm version 
          helm repo add litmuschaos https://litmuschaos.github.io/litmus-portal
          helm install litmuschaos/litmus-portal --version 3.16.0 --namespace litmus-system --create-namespace --set serverAddress=http://localhost:31674/api/query --set accessKey=F9boAe-VV5isT7VBLAAraF19b3G6nvqA --set instanceID=a56d3cf8-04d4-41c3-95ac-32f3aa1fbca2 --set skipSSLVerify=true
          
      - name: Run chart-testing (install)
        run: ct install --config ct.yaml  --upgrade 
